version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    restart: unless-stopped
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
